### ISSUE TITLE
Module 2: Lab 5 - NSGs : port 3389 exposed to internet and the information has to be changed

### ISSUE THREAD

**Issue by bandarunagesh** [MicrosoftLearning/AZ-500-Azure-Security#170]
# Module: 00
#### Step: 00

Description of issue

Repro steps:
Please review 'Task 9: Test traffic filters' it was mentioned that 'You can't, however, create a remote desktop connection to the myVmWeb VM from the internet because the security rule for the myAsgWebServers doesn't allow port 3389 inbound from the internet, and inbound traffic from the Internet is denied to all resources, by default.'

But if you see the step  Task 5 (Step 3) already port 3389 exposed over internet and we can able to connect to VM over internet.

I hope, the Task 5(Step 3) has to be removed, so that we can can not connect to myVmWeb VM over internet but through myVmMgmt as they communicate  with in the same Vnet

1.
1.
1.

**Comment by garethjones294** [comment]
Hi,

The lab is correct, you are exposing 3389 for the myAsgMgmtServers and not the myAsgWebServers therefore the outcome of the lab as expected.  In the real world the Mgmt servers would not be exposed as per the note:

In this tutorial, RDP (port 3389) is exposed to the internet for the VM that is assigned to the myAsgMgmtServers application security group. For production environments, instead of exposing port 3389 to the internet, it's recommended that you connect to Azure resources that you want to manage using a VPN or private network connection.

Regards
